version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: yarn
      - run:
          name: Install dependencies
          command: sudo apt-get -y -qq install awscli 
      - run: 
          name: zip folder
          command: |
            cd ../
            zip -r aws-lambda.zip project -x "*.DS_Store"
      - run:
          name: Push zip folder to s3
          command: |
            aws s3 cp ../aws-lambda.zip s3://alexa-odds-checker



