version: 2
  jobs:
    deploy:
      steps:
        - checkout
        - run: yarn
        - run: 
            name: Zip aws-lambda file.
            command: |
              zip -r my-folder.zip my-folder -x "*.DS_Store"
        - run:
            name: Push zip folde to s3
            command: |
              aws s3 cp aws-lambda.zip https://s3.console.aws.amazon.com/s3/buckets/alexa-odds-checker



